/**
 * Intrinsic pixel size of every file in public/images, generated by
 * scripts/measure-images.mjs. Do not edit by hand — re-run the script.
 *
 * The gallery needs real dimensions to render each image at its own aspect
 * ratio. Without them every image has to be forced into one fixed box, and
 * the 2.4:1 campaign banners end up letterboxed inside a 16:10 frame with
 * bands of dead space above and below.
 */
export const IMAGE_DIMS: Record<string, [number, number]> = {
  "/images/air-ultra-6-in-1-01.webp": [2400, 1485],
  "/images/air-ultra-6-in-1-02.webp": [2400, 1485],
  "/images/air-ultra-6-in-1-03.webp": [2400, 1493],
  "/images/air-ultra-6-in-1-04.webp": [2400, 1485],
  "/images/air-ultra-6-in-1-05.webp": [2400, 1485],
  "/images/air-ultra-6-in-1-m01.jpeg": [1254, 1254],
  "/images/air-ultra-6-in-1-m02.jpeg": [1254, 1254],
  "/images/air-ultra-6-in-1-m03.jpeg": [1600, 655],
  "/images/air-ultra-6-in-1-m04.jpeg": [1600, 657],
  "/images/air-ultra-6-in-1-m05.jpeg": [1600, 656],
  "/images/air-ultra-6-in-1-m06.jpeg": [1535, 1024],
  "/images/air-ultra-6-in-1-m07.jpeg": [1254, 1254],
  "/images/air-ultra-6-in-1-m08.jpeg": [1402, 1122],
  "/images/air-ultra-6-in-1-m09.jpeg": [1535, 1024],
  "/images/air-ultra-6-in-1-m10.jpeg": [1535, 1024],
  "/images/air-ultra-6-in-1-m11.jpeg": [1535, 1024],
  "/images/air-ultra-6-in-1-m12.jpeg": [1402, 1122],
  "/images/air-ultra-6-in-1-m13.jpeg": [1402, 1122],
  "/images/air-ultra-6-in-1-m14.jpeg": [1254, 1254],
  "/images/air-ultra-6-in-1-m15.jpeg": [1254, 1254],
  "/images/air-ultra-pro-01.webp": [2400, 1493],
  "/images/air-ultra-pro-02.webp": [2400, 1485],
  "/images/air-ultra-pro-03.webp": [2400, 1493],
  "/images/air-ultra-pro-04.webp": [2400, 1493],
  "/images/air-ultra-pro-05.webp": [2400, 1493],
  "/images/air-ultra-pro-m01.jpeg": [1536, 1024],
  "/images/air-ultra-pro-m02.jpeg": [1536, 1024],
  "/images/air-ultra-pro-m03.jpeg": [1536, 1024],
  "/images/air-ultra-pro-m04.jpeg": [1254, 1254],
  "/images/air-ultra-pro-m05.jpeg": [1600, 657],
  "/images/air-ultra-pro-m06.jpeg": [1600, 656],
  "/images/air-ultra-pro-m07.jpeg": [1600, 656],
  "/images/air-ultra-pro-m08.jpeg": [1369, 1149],
  "/images/air-ultra-pro-m09.jpeg": [1402, 1122],
  "/images/air-ultra-pro-package.jpeg": [1376, 768],
  "/images/air-vision-ai-01.webp": [2400, 1485],
  "/images/air-vision-ai-02.webp": [2400, 1485],
  "/images/air-vision-ai-03.webp": [2400, 1485],
  "/images/air-vision-ai-04.webp": [2400, 1485],
  "/images/air-vision-ai-05.webp": [2400, 1485],
  "/images/easycook-2000w-01.webp": [2400, 2400],
  "/images/infranova-3500w-01.webp": [1024, 571],
  "/images/infranova-3500w-02.webp": [1024, 419],
  "/images/infranova-3500w-03.webp": [1024, 419],
  "/images/mojo-01.webp": [679, 679],
  "/images/mojo-02.webp": [679, 679],
  "/images/mojo-03.webp": [679, 679],
  "/images/mojo-04.webp": [1000, 1000],
  "/images/mojo-05.webp": [679, 679],
  "/images/mojo-06.webp": [1000, 1000],
  "/images/mojo-07.webp": [679, 679],
  "/images/mojo-08.webp": [1000, 1000],
  "/images/rockbox-vintage-01.webp": [679, 679],
  "/images/silkcomb-cordless-01.webp": [1024, 571],
  "/images/silkcomb-cordless-02.webp": [1920, 1080],
  "/images/silkcomb-cordless-03.webp": [1920, 1080],
  "/images/silkcomb-cordless-hero.webp": [1920, 1080],
  "/images/silkcomb-cordless-package.webp": [345, 330],
  "/images/silkcomb-cordless-product.webp": [1920, 1080],
  "/images/styler-travel-case-01.webp": [679, 507],
  "/images/styler-travel-case-02.webp": [528, 504],
};

/** Falls back to 4:3 for anything unmeasured — wrong, but never zero. */
export const dimsOf = (src: string): [number, number] =>
  IMAGE_DIMS[src] ?? [1200, 900];
