/**
 * Regenerates lib/image-dims.ts from whatever is in public/images.
 * Run it after adding or replacing images:  node scripts/measure-images.mjs
 *
 * Reads the pixel size straight out of the file headers rather than pulling in
 * an image library for something that is a dozen lines of byte arithmetic.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const DIR = "public/images";

/** JPEG: walk the segment markers to the SOF frame header. */
const jpeg = (b) => {
  let i = 2;
  while (i < b.length) {
    if (b[i] !== 0xff) { i++; continue; }
    const m = b[i + 1];
    const isSOF = m >= 0xc0 && m <= 0xcf && m !== 0xc4 && m !== 0xc8 && m !== 0xcc;
    if (isSOF) return [b.readUInt16BE(i + 7), b.readUInt16BE(i + 5)];
    i += 2 + b.readUInt16BE(i + 2);
  }
  return null;
};

/** WebP has three container flavours and each stores the size differently. */
const webp = (b) => {
  const kind = b.toString("ascii", 12, 16);
  if (kind === "VP8X") return [1 + b.readUIntLE(24, 3), 1 + b.readUIntLE(27, 3)];
  if (kind === "VP8L") {
    const bits = b.readUInt32LE(21);
    return [1 + (bits & 0x3fff), 1 + ((bits >> 14) & 0x3fff)];
  }
  return [b.readUInt16LE(26) & 0x3fff, b.readUInt16LE(28) & 0x3fff];
};

const dims = {};
for (const f of readdirSync(DIR)) {
  const buf = readFileSync(`${DIR}/${f}`);
  const d = /\.webp$/i.test(f) ? webp(buf) : /\.jpe?g$/i.test(f) ? jpeg(buf) : null;
  if (d) dims[`/images/${f}`] = d;
}

const body = Object.entries(dims)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([k, [w, h]]) => `  "${k}": [${w}, ${h}],`)
  .join("\n");

writeFileSync(
  "lib/image-dims.ts",
  `/**
 * Intrinsic pixel size of every file in public/images, generated by
 * scripts/measure-images.mjs. Do not edit by hand — re-run the script.
 *
 * The gallery needs real dimensions to render each image at its own aspect
 * ratio. Without them every image has to be forced into one fixed box, and
 * the 2.4:1 campaign banners end up letterboxed inside a 16:10 frame with
 * bands of dead space above and below.
 */
export const IMAGE_DIMS: Record<string, [number, number]> = {
${body}
};

/** Falls back to 4:3 for anything unmeasured — wrong, but never zero. */
export const dimsOf = (src: string): [number, number] =>
  IMAGE_DIMS[src] ?? [1200, 900];
`,
);

console.log(`measured ${Object.keys(dims).length} images`);
